### ISSUE TITLE
Voices crackles

### ISSUE THREAD

**Issue by DetErDugget** [TGIANN/tgiann-voice-effect#1]
Not sure if it's because we're using an external voice server.

Non the less, we get crackling sounds, as if the audio cables is broke, when we use this script :( 

No crackling, when we disable this script, and restart the external voice server.

If i reenable this awesome script, it starts to crackle and lag for everyone.

Do you have any suggestions?

**Comment by DetErDugget** [comment]
It seems to cut out the whole games sounds aswell

**Comment by LikeManTV** [comment]
I can confirm this issue.
The in-game audio becomes choppy while using the script.

**Comment by DetErDugget** [comment]
> I can confirm this issue. The in-game audio becomes choppy while using the script.

Do you also use an external voice CFX server?

**Comment by LikeManTV** [comment]
> Do you also use an external voice CFX server?

No just regular pma-voice setup.

**Comment by DetErDugget** [comment]
> > Do you also use an external voice CFX server?
> 
> No just regular pma-voice setup.

Roger that. So you use PMA-voice,

Let's try to compare our resources regarding voice.

I use 
 - PMA Voice with external voice server
 - LB Phone
 - QB-radio
 
 We also have a player base of 120-140 players, maybe the quantity of players is where we get issues?

**Comment by DetErDugget** [comment]
Also we're using the following PMA settings in server.cfg: 
setr voice_useNativeAudio true
setr voice_useSendingRangeOnly true
setr voice_enableRadioSubmix 1
setr voice_defaultCycle "GRAVE"
setr voice_defaultVolume 0.3
setr voice_enableRadioAnim 1

**Comment by LikeManTV** [comment]
> > > Do you also use an external voice CFX server?
> > 
> > 
> > No just regular pma-voice setup.
> 
> Roger that. So you use PMA-voice,
> 
> Let's try to compare our resources regarding voice.
> 
> I use
> 
> * PMA Voice with external voice server
> * LB Phone
> * QB-radio
> 
> We also have a player base of 120-140 players, maybe the quantity of players is where we get issues?

The server isn't public, we use almost the same resources (except qb scripts).
I don't think the issue is related to this. But I've already contacted the author so let's hope this gets resolved.

**Comment by francodamian** [comment]
Hi, we have the same problem, did anyone found a fix ? we using 3095 and last artifacts recommended by txadmin

we already try all the versions of the script and still breaks the audio

**Comment by LikeManTV** [comment]
> Hi, we have the same problem, did anyone found a fix ? we using 3095 and last artifacts recommended by txadmin
> 
> we already try all the versions of the script and still breaks the audio

Hey, I don't think there's a fix yet.
I don't even know what could be the cause of this issue.

**Comment by TGIANN** [comment]
pls try with this version: https://github.com/AvarianKnight/pma-voice/releases/tag/v6.6.2

**Comment by francodamian** [comment]
> pls try with this version: https://github.com/AvarianKnight/pma-voice/releases/tag/v6.6.2

still the same, the audio starts to breaks when other player joins

**Comment by TenJackie** [comment]
I think turning off vehicleInside fixes the crackling issue.

```
        -- Muffled hearing of those outside the vehicle
        vehicleInside = {
            active = false,
```

**Comment by LikeManTV** [comment]
> I think turning off vehicleInside fixes the crackling issue.
> 
> ```
>         -- Muffled hearing of those outside the vehicle
>         vehicleInside = {
>             active = false,
> ```

I will definitely try this but for me the issue with sound applied to everything not just the voice chat.

**Comment by francodamian** [comment]
> I think turning off vehicleInside fixes the crackling issue.
> 
> ```
>         -- Muffled hearing of those outside the vehicle
>         vehicleInside = {
>             active = false,
> ```

i already try this also try to change the pma version, still audio breaks

**Comment by LikeManTV** [comment]
Maybe fixed with the latest Community Pulse? (Didn't test yet)

Fixed an issue causing corrupt audio when using too many [submixes 23](https://docs.fivem.net/docs/scripting-manual/voice/#submixes).

**Comment by DetErDugget** [comment]
> Maybe fixed with the latest Community Pulse? (Didn't test yet)
> 
> Fixed an issue causing corrupt audio when using too many [submixes 23](https://docs.fivem.net/docs/scripting-manual/voice/#submixes).

Please let me know if it works, the desire for this to work for us, is very high :D

**Comment by LikeManTV** [comment]
> Please let me know if it works, the desire for this to work for us, is very high :D

Sure, I will let you know.

**Comment by LikeManTV** [comment]
Hey @DetErDugget 
I can confirm that the issue is still present with the latest artifacts.
Unfortunately didn't a way to fix this.

One thing I found out is that this issue is over a year old.
There seems to be a limit of the maximum submixes which is **40** and **28** are reserved by the game. Anything above **12** clobbers subsequent audio driver fields.

**Comment by DetErDugget** [comment]
> Hey @DetErDugget I can confirm that the issue is still present with the latest artifacts. Unfortunately didn't a way to fix this.
> 
> One thing I found out is that this issue is over a year old. There seems to be a limit of the maximum submixes which is **40** and **28** are reserved by the game. Anything above **12** clobbers subsequent audio driver fields.

Okay thanks for sharing, i've added this issue on the CFX github issues.
